ARG PHP_VERSION
FROM ghcr.io/iksaku/laravel-alpine:${PHP_VERSION}-cli

# Overwrite entrypoint to use Octane
RUN sed -i \
    's/artisan serve/artisan octane:start --server=roadrunner --rpc-port=6001/' \
    /usr/local/bin/start-server

# Install PHP extensions required by Octane
RUN install-php-extensions sockets

# Install RoadRunner binary
COPY --from=ghcr.io/roadrunner-server/roadrunner:latest /usr/bin/rr /usr/local/bin/rr
