name: Image Builder

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 7 * * 1'

jobs:
  build:
    name: php-${{ matrix.php }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        php:
          - '8.0'
          - '8.1'
          - '8.2'
    steps:
      - name: Get Latest PHP Version
        id: php
        run: |
          echo "version=$(docker run --rm php:${{ matrix.php }}-cli-alpine php -r 'echo PHP_VERSION;')" >> $GITHUB_OUTPUT
          echo "release=$(docker run --rm php:${{ matrix.php }}-cli-alpine php -r 'echo PHP_RELEASE_VERSION;')" >> $GITHUB_OUTPUT

      - name: Check if Image is up to date
        id: check
        run: |
          CURRENT_VERSION=$(docker run --rm ghcr.io/iksaku/laravel-alpine:${{ matrix.php }} php -r 'echo PHP_VERSION;')
          if [ "${{ steps.php.outputs.version }}" == "$CURRENT_VERSION" ]; then
            echo "PHP version is up to date: v${{ steps.php.outputs.version }}"
          else
            echo "PHP version is outdated. Got v$CURRENT_VERSION, expected v${{ steps.php.outputs.version }}"
            echo "continue=true" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Code
        if: ${{ steps.check.outputs.continue == 'true' }}
        uses: actions/checkout@v3

      - name: Get Docker Context
        if: ${{ steps.check.outputs.continue == 'true' }}
        id: docker_context
        run: echo "context=$(echo ${{ matrix.php }} | sed -r 's/^([0-9]+)\..*$/\1.x/')" >> $GITHUB_OUTPUT

      - name: Generate Image Metadata
        if: ${{ steps.check.outputs.continue == 'true' }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/iksaku/laravel-alpine
          tags: |
            type=raw,${{ matrix.php }}
            type=raw,${{ matrix.php }}.${{ steps.php.outputs.release }}

      - name: Set up QEMU
        if: ${{ steps.check.outputs.continue == 'true' }}
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: ${{ steps.check.outputs.continue == 'true' }}
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: ${{ steps.check.outputs.continue == 'true' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ steps.check.outputs.continue == 'true' }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ steps.docker_context.outputs.context }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}

  build_octane:
    name: php-${{ matrix.php }} octane-${{ matrix.runtime }}
    runs-on: ubuntu-latest
    timeout-minutes: 40
    needs: build
    strategy:
      matrix:
        php:
          - '8.0'
          - '8.1'
          - '8.2'
        runtime:
          - roadrunner
          - swoole
    steps:
      - name: Get Latest (Non-Octane Image) PHP version
        id: standalone
        run: |
          echo "version=$(docker run --rm ghcr.io/iksaku/laravel-alpine:${{ matrix.php }} php -r 'echo PHP_VERSION;')" >> $GITHUB_OUTPUT
          echo "release=$(docker run --rm ghcr.io/iksaku/laravel-alpine:${{ matrix.php }} php -r 'echo PHP_RELEASE_VERSION;')" >> $GITHUB_OUTPUT

      - name: Get Latest ${{ matrix.runtime }} version
        id: runtime
        run: |
          if [ "${{ matrix.runtime }}" == "roadrunner" ]; then
            LATEST_RUNTIME_VERSION=$(docker run --rm ghcr.io/roadrunner-server/roadrunner:latest -v | sed -r 's/^rr version ([0-9\.]+) .*/\1/')
          elif [ "${{ matrix.runtime }}" == "swoole" ]; then
            LATEST_RUNTIME_VERSION=$(docker run --rm phpswoole/swoole:5.0-php${{ matrix.php }}-alpine php -r 'echo swoole_version();')
          fi
          
          echo "version=$LATEST_RUNTIME_VERSION" >> $GITHUB_OUTPUT

      - name: Check if Image is up to date
        id: check
        run: |
          CURRENT_PHP_VERSION=$(docker run --rm ghcr.io/iksaku/laravel-alpine:${{ matrix.php }}-octane-${{ matrix.runtime }} php -r 'echo PHP_VERSION;')
          if [ "${{ steps.standalone.outputs.version }}" == "$CURRENT_PHP_VERSION" ]; then
            echo "PHP version is up to date: v${{ steps.standalone.outputs.version }}"
          else
            echo "PHP version is outdated. Got v$CURRENT_PHP_VERSION, expected v${{ steps.standalone.outputs.version }}"
            echo "continue=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          if [ "${{ matrix.runtime }}" == "roadrunner" ]; then
            CURRENT_RUNTIME_VERSION=$(docker run --rm ghcr.io/iksaku/laravel-alpine:${{ matrix.php }}-octane-${{ matrix.runtime }} rr -v | sed -r 's/^rr version ([0-9\.]+) .*/\1/')
          elif [ "${{ matrix.runtime }}" == "swoole" ]; then
            CURRENT_RUNTIME_VERSION=$(docker run --rm ghcr.io/iksaku/laravel-alpine:${{ matrix.php }}-octane-${{ matrix.runtime }} php -r 'echo swoole_version();')
          fi
          
          if [ "${{ steps.runtime.outputs.version }}" == "$CURRENT_RUNTIME_VERSION" ]; then
            echo "Runtime version is up to date: v${CURRENT_RUNTIME_RELEASE}"
          else
            echo "Runtime version is outdated. Got v$CURRENT_RUNTIME_VERSION, expected v${{ steps.runtime.outputs.version }}"
            echo "continue=true" >> $GITHUB_OUTPUT
            exit 0
          fi

      - name: Checkout Code
        if: ${{ steps.check.outputs.continue == 'true' }}
        uses: actions/checkout@v3

      - name: Get Docker Context
        if: ${{ steps.check.outputs.continue == 'true' }}
        id: docker_context
        run: echo "context=$(echo ${{ matrix.php }} | sed -r 's/^([0-9]+)\..*$/\1.x/')" >> $GITHUB_OUTPUT

      - name: Generate Image Metadata
        if: ${{ steps.check.outputs.continue == 'true' }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/iksaku/laravel-alpine
          tags: |
            type=raw,${{ matrix.php }}-octane-${{ matrix.runtime }}
            type=raw,${{ matrix.php }}.${{ steps.standalone.outputs.release }}-octane-${{ matrix.runtime }}
            type=raw,${{ matrix.php }}.${{ steps.standalone.outputs.release }}-octane-${{ matrix.runtime }}-${{ steps.runtime.outputs.version }}

      - name: Set up QEMU
        if: ${{ steps.check.outputs.continue == 'true' }}
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: ${{ steps.check.outputs.continue == 'true' }}
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: ${{ steps.check.outputs.continue == 'true' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ steps.check.outputs.continue == 'true' }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ steps.docker_context.outputs.context }}
          file: ${{ steps.docker_context.outputs.context }}/Dockerfile.octane.${{ matrix.runtime }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
