name: Image Builder

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 7 * * 1'

jobs:
  build:
    name: laravel-alpine:${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1]
    env:
      IMAGE: ghcr.io/iksaku/laravel-alpine:${{ matrix.php }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Build PHP ${{ matrix.php }} image
        run: |
          docker build -t ${IMAGE} ${{ matrix.php }}

          RELEASE=$(docker run --rm ${IMAGE} /bin/sh php -r 'echo PHP_RELEASE_VERSION;')
          docker tag ${IMAGE} ${IMAGE}.${RELEASE}

          docker image ls ${IMAGE}

      - name: Push Image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker push --all-tags ghcr.io/iksaku/laravel-alpine

  build_octane:
    name: laravel-alpine:${{ matrix.php }}-octane-${{ matrix.runtime }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        php: [8.1]
        runtime: ['roadrunner', 'swoole']
    env:
      IMAGE: ghcr.io/iksaku/laravel-alpine:${{ matrix.php }}-octane-${{ matrix.runtime }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build PHP ${{ matrix.php }} and Octane Runtime '${{ matrix.runtime }}'
        run: |
          docker build \
            --build-arg PHP_VERSION=${{ matrix.php }} \
            -t ${IMAGE} \
            -f ${{ matrix.php }}/Dockerfile.octane.${{ matrix.runtime }} \
            ${{ matrix.php }}
          
          RELEASE=$(docker run --rm ${IMAGE} /bin/sh php -r 'echo PHP_RELEASE_VERSION;')
          docker tag ${IMAGE} \
            $(sed "s/${{ matrix.php }}-/${{ matrix.php }}.${RELEASE}-/" <<< ${IMAGE})

          docker image ls ghcr.io/iksaku/laravel-alpine

      - name: Push Image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          
          docker push --all-tags ghcr.io/iksaku/laravel-alpine
